// Code generated by raiden-cli; DO NOT EDIT.
package bootstrap

import (
	"github.com/sev-2/raiden/pkg/resource"
	"medpoint/internal/models"
)

func RegisterModels() {
	resource.RegisterModels(
		&models.Addresses{},
		&models.Appointments{},
		&models.DoctorSchedules{},
		&models.Doctors{},
		&models.HealthcareFacilities{},
		&models.MedicalRecords{},
		&models.Payments{},
		&models.SpecialityCategories{},
		&models.Users{},
	)
}
