// Code generated by raiden-cli; DO NOT EDIT.
package bootstrap

import (
	"github.com/sev-2/raiden"
	raiden_controllers "github.com/sev-2/raiden/pkg/controllers"
	"github.com/valyala/fasthttp"
	"medpoint/internal/controllers"
	"medpoint/internal/models"
)

func RegisterRoute(server *raiden.Server) {
	server.RegisterRoute([]*raiden.Route{
		raiden.NewRouteFromController(&raiden_controllers.StateReadyController{}, []string{fasthttp.MethodPost}),
		{
			Type:       raiden.RouteTypeCustom,
			Path:       "/doctor",
			Methods:    []string{fasthttp.MethodPost, fasthttp.MethodGet},
			Controller: &controllers.DoctorController2{},
		},
		{
			Type:       raiden.RouteTypeRest,
			Path:       "/doctor/{doctor_id}",
			Methods:    []string{fasthttp.MethodGet, fasthttp.MethodPut, fasthttp.MethodDelete},
			Controller: &controllers.DoctorController1{},
			Model:      models.Doctors{},
		},
		{
			Type:       raiden.RouteTypeCustom,
			Path:       "/hello",
			Methods:    []string{fasthttp.MethodGet},
			Controller: &controllers.HelloWorldController{},
		},
	})
}
