PROJECT_NAME: Medpoint
PROJECT_ID: lotpaaakejmnmbrmgqcb
DEPLOYMENT_TARGET: cloud

MODE: bff


ACCESS_TOKEN: sbp_dbc9bb891e8e6d0d81524cd99a7206c8aaaae087
ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvdHBhYWFrZWptbm1icm1ncWNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcxMTAyMDksImV4cCI6MjA1MjY4NjIwOX0.JHnb9xfAIz9CfU0qGqXKJBLFNVhWYeDG1-8fBxI_U_I
SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvdHBhYWFrZWptbm1icm1ncWNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcxMTAyMDksImV4cCI6MjA1MjY4NjIwOX0.JHnb9xfAIz9CfU0qGqXKJBLFNVhWYeDG1-8fBxI_U_I

SUPABASE_API_URL: https://api.supabase.com
SUPABASE_API_BASE_PATH: 
SUPABASE_PUBLIC_URL: https://lotpaaakejmnmbrmgqcb.supabase.co

SERVER_HOST: 127.0.0.1
SERVER_PORT: 8002
SERVER_DNS: 

ENVIRONMENT: development
VERSION: 1.0.0

ALLOWED_TABLES: 

SCHEDULE_STATUS: 'off'

BREAKER_ENABLE: true

TRACE_ENABLE: false
TRACE_COLLECTOR: 
TRACE_COLLECTOR_ENDPOINT: 

MAX_SERVER_REQUEST_BODY_SIZE: 8388608

CORS_ALLOWED_ORIGINS:
CORS_ALLOWED_METHODS:
CORS_ALLOWED_HEADERS:
